### ISSUE TITLE
Proper name

### ISSUE THREAD

**Issue by nirrattner** [kmclarnon/SmashDB#2]
How do we feel about calling it GameAndWatch? I already know an appropriate mascot
![gw](https://cloud.githubusercontent.com/assets/12188516/15089506/66d10644-13d2-11e6-9cd4-4d991460b7a6.jpg)

**Comment by kmclarnon** [comment]
Haha i'm cool with that

**Comment by nirrattner** [comment]
As far domain names go, both gameandwatch.com and gameandwat.ch are taken

**Comment by kmclarnon** [comment]
[gameandwatch.tk](http://my.dot.tk/registration/register?domainname=gameandwatch) is available, so are a [bunch of others](https://www.namecheap.com/domains/registration/results.aspx?domain=gameandwatch&tlds=io) but most of them you have to pay for

**Comment by nirrattner** [comment]
gameandwatching.us purchased! Now just to rename. I think we agree on package us.gameandwatching.gwapi.*
